#server:
#  port: 8080  # Spring boot Server port

spring:
#  h2:
#    console:
#      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
#      path: /test_db  # 콘솔의 경로

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:tcp://localhost/~/jwp-chess-web  #접속 URL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true